from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from database import engine, Base
import models  # noqa

from routers import (
    auth_router,
    docentes_router,
    estudiantes_router,
    anotaciones_router,
    reportes_router,
)

Base.metadata.create_all(bind=engine)


def crear_admin_inicial():
    from database import SessionLocal
    from auth import hashear_contrasena
    db = SessionLocal()
    try:
        USUARIOS = [
            ("Alexander", "Padilla", "admin", "jairpadillaaxec@gmail.com", "docente2026", "admin", "INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA"),
            ("David", "Salazar", "rector", None, "rector2026", "admin", "INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA"),
            ("Coordinacion", "Uriel Murcia", "coordinacion", None, "coord2026", "coordinador", "INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA"),
        ]
        for nombres, apellidos, doc, email, pwd, rol, sede in USUARIOS:
            if db.query(models.Usuario).filter(models.Usuario.documento == doc).first():
                continue
            u = models.Usuario(
                nombres=nombres, apellidos=apellidos, documento=doc,
                email=email, contrasena_hash=hashear_contrasena(pwd),
                rol=rol, sede=sede, activo=True
            )
            db.add(u)
        db.commit()
    except Exception as e:
        print(f"Error creando usuarios: {e}")
        db.rollback()
    finally:
        db.close()


def importar_estudiantes_inicial():
    from database import SessionLocal
    db = SessionLocal()
    try:
        if db.query(models.Estudiante).count() > 0:
            return
        ESTUDIANTES = [
            ('GABRIELA', 'VIRGUEZ MONTENEGRO', '1069054920', 'ESCUELA RURAL  PASURCHA', 'CUARTO', '401', 8, None),
            ('ERIK MATEO', 'CARDENAS FLORIDO', '1032501088', 'ESCUELA RURAL  PASURCHA', 'CUARTO', '401', 9, None),
            ('SHANI ZIREL', 'BUSTOS SANCHEZ', '1057097244', 'ESCUELA RURAL CABO VERDE', 'PRIMERO', '101', 5, None),
            ('JOHAN GAHEL', 'SOTO GARZON', '1074996408', 'ESCUELA RURAL CABO VERDE', 'TERCERO', '301', 7, None),
            ('ERICK JAVIER', 'CASTAÑEDA CARDOSO', '1074996238', 'ESCUELA RURAL CABO VERDE', 'CUARTO', '401', 9, None),
            ('JUAN DAVID', 'AGUIRRE GARZON', '1074996068', 'ESCUELA RURAL CABO VERDE', 'QUINTO', '501', 10, None),
            ('ANGEL DAVID', 'SANCHEZ FLORIDO', '1111207191', 'ESCUELA RURAL EL BANCO', 'GRADO 0', '1', 4, None),
            ('HARWALL SAMUEL', 'ROJAS VEGA', '1057390448', 'ESCUELA RURAL EL BANCO', 'PRIMERO', '101', 5, None),
            ('KAROL XIMENA', 'MARROQUIN AGUIRRE', '1078829144', 'ESCUELA RURAL EL BANCO', 'TERCERO', '301', 7, None),
            ('JUAN JOSE', 'LOPEZ FLORIDO', '1028702046', 'ESCUELA RURAL EL BANCO', 'QUINTO', '501', 10, None),
            ('SHARON ISABELA', 'AGUIRRE PACHON', '1074996513', 'ESCUELA RURAL EL CHAPON', 'PRIMERO', '101', 5, None),
            ('ALEJANDRO', 'VASQUEZ FLORIDO', '1025331537', 'ESCUELA RURAL EL CHAPON', 'PRIMERO', '101', 5, None),
            ('ARIANA', 'AGUIRRE ALVAREZ', '1057390407', 'ESCUELA RURAL EL CHAPON', 'CUARTO', '401', 9, None),
            ('VICTORIA HELENA', 'TAMAYO ALVAREZ', '1013028511', 'ESCUELA RURAL EL CHAPON', 'CUARTO', '401', 9, None),
            ('VALENTINA', 'TELLEZ VIRGUEZ', '1074996236', 'ESCUELA RURAL EL CHAPON', 'CUARTO', '401', 9, None),
            ('JOEL SANTIAGO', 'QUIROGA VASALLO', '1104714000', 'ESCUELA RURAL EL LAMAL', 'GRADO 0', '1', 5, None),
            ('ELIAN ALEXANDER', 'CAMACHO LOZADA', '1074996570', 'ESCUELA RURAL EL LAMAL', 'GRADO 0', '1', 5, None),
            ('SELESTE', 'RAMOS ANZOLA', '1036226472', 'ESCUELA RURAL EL LAMAL', 'SEGUNDO', '201', 7, None),
            ('JUAN SEBASTIAN', 'ANZOLA ALVAREZ', '1036226046', 'ESCUELA RURAL EL LAMAL', 'TERCERO', '301', 8, None),
            ('ANGEL DAVID', 'GONZALEZ MARTINEZ', '1121965346', 'ESCUELA RURAL EL LAMAL', 'TERCERO', '301', 8, None),
            ('ALINZON ANDREY', 'ANZOLA ALVAREZ', '1074960759', 'ESCUELA RURAL EL LAMAL', 'CUARTO', '401', 12, None),
            ('LORAIME MICAELA', 'ANZOLA ALVAREZ', '1162963228', 'ESCUELA RURAL EL LAMAL', 'CUARTO', '401', 11, None),
            ('JHORDANA MICHELL', 'VIZCAINO GAVIRIA', '1083579352', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'GRADO 0', '1', 5, None),
            ('LEZLY ELIZABETH', 'PINILLA ROMERO', '1074996542', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'GRADO 0', '1', 5, None),
            ('NIKOLL SOPHIA', 'BUSTOS LANCHEROS', '1074996458', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'SEGUNDO', '201', 7, None),
            ('JORGE ANDRES', 'SEGURA VEGA', '1069944786', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'SEGUNDO', '201', 7, None),
            ('SAMMY ALEJANDRA', 'GARCIA VEGA', '1074960733', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'CUARTO', '401', 12, None),
            ('JAZMIN VALERIA', 'BECERA FLORIDO', '1028792829', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'CUARTO', '401', 9, None),
            ('SALOME', 'AGUILAR LOPEZ', '1054568425', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'QUINTO', '501', 10, None),
            ('LUISA FERNANDA', 'GUACANEME FLORIDO', '1033800841', 'ESCUELA RURAL LOS ANGELES DE APOSENTOS', 'QUINTO', '501', 10, None),
            ('TANIA VALENTINA', 'RAMIREZ MARROQUIN', '1233919226', 'ESCUELA RURAL YASAL ALTO', 'GRADO 0', '1', 6, None),
            ('JEAN PAUL', 'VEGA ALVAREZ', '1074996563', 'ESCUELA RURAL YASAL ALTO', 'GRADO 0', '1', 5, None),
            ('MIGUEL ANGEL', 'BUSTOS SOTO', '1074996518', 'ESCUELA RURAL YASAL ALTO', 'PRIMERO', '101', 5, None),
            ('VIOLLET MALENA', 'TORRES TRIANA', '1162964231', 'ESCUELA RURAL YASAL ALTO', 'SEGUNDO', '201', 7, None),
            ('ANDERSON MATEO', 'MAHECHA ALVAREZ', '1074996346', 'ESCUELA RURAL YASAL ALTO', 'TERCERO', '301', 8, None),
            ('JUAN ESTEBAN', 'LEON BERNAL', '1071632091', 'ESCUELA RURAL YASAL ALTO', 'TERCERO', '301', 8, None),
            ('ALAN JULIAN', 'RAMIREZ MARROQUIN', '1016740244', 'ESCUELA RURAL YASAL ALTO', 'CUARTO', '401', 10, None),
            ('MICHAEL EMANUEL', 'CUCAITA CASALLAS', '1141720704', 'ESCUELA RURAL YASAL ALTO', 'QUINTO', '501', 14, None),
            ('KAREN YULIANA', 'SOTO CARRILLO', '1074996032', 'ESCUELA RURAL YASAL ALTO', 'QUINTO', '501', 10, None),
            ('EILI SAMARA', 'ORDOÑEZ ESCARRAGA', '1189963807', 'ESCUELA RURAL YASAL BAJO', 'SEGUNDO', '201', 7, None),
            ('EMILY DANIELA', 'DIAZ ESCARRAGA', '1111206052', 'ESCUELA RURAL YASAL BAJO', 'SEGUNDO', '201', 8, None),
            ('MADELEYN SAMARA', 'JIMENEZ LOZANO', '1023973791', 'ESCUELA RURAL YASAL BAJO', 'CUARTO', '401', 9, None),
            ('YISEL YULIANA', 'RUEDA SOTO', '1074996012', 'ESCUELA RURAL YASAL BAJO', 'QUINTO', '501', 10, None),
            ('CARLOS ANDRES', 'FLORIDO HERNANDEZ', '1074960993', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 11, None),
            ('JEAN JADIR', 'VANEGAS VEGA', '1028894582', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 12, None),
            ('BRIYITH JULIANA', 'BERNAL BURBANO', '1074960908', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 11, None),
            ('LAURA ISABELLA', 'ESCARRAGA TRIANA', '1025551960', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 12, None),
            ('KLAR JEREMY', 'JIMENEZ LOZANO', '1023947445', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 12, None),
            ('CAMILO', 'SASTRE TELLEZ', '1074996038', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEXTO', '601', 10, None),
            ('VALERI NICOL', 'BUSTOS ESCARRAGA', '1033770789', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 13, None),
            ('JHAROL STEVEN', 'ESCARRAGA SOTELO', '1033788486', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 11, None),
            ('SHEILA SOFIA', 'ESCARRAGA TRIANA', '1025548509', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 14, None),
            ('NICOL JULIANA', 'FLORIDO FLORIDO', '1074960860', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 12, None),
            ('ZURISADAI', 'SOTO FLORIDO', '1057390331', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 12, None),
            ('VALERIE TALIANA', 'SANCHEZ FLORIDO', '1111202238', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 12, None),
            ('BRANDON NICOLAS', 'RAMIREZ AGUIRRE', '1031162056', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'SEPTIMO', '701', 12, None),
            ('JUAN CAMILO', 'ALVAREZ HOYOS', '1074960555', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('WENDY TATIANA', 'ESCOBAR VILLAMARIN', '1074960506', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('SANTIAGO', 'MARROQUIN FLORIDO', '1033112106', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('JONEIDA ALEXANDRA', 'REYES RUEDA', '1074960674', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('JUAN SEBASTIAN', 'SASTRE BOTACHE', '1074960679', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('JUAN FELIPE', 'SASTRE TELLEZ', '1021685178', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 13, None),
            ('ELKIN ALEJANDRO', 'BERNAL BURBANO', '1074960306', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'OCTAVO', '801', 14, None),
            ('KEINER SANTIAGO', 'AGUILAR CIFUENTES', '1025549246', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 13, None),
            ('NICY YULITZA', 'CULMA PEDRAZA', '1189963295', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 14, None),
            ('DILAN ARCESIO', 'ESCARRAGA LINARES', '1074960454', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 14, None),
            ('KAREN YULIE', 'ESCOBAR VILLAMARIN', '1141329599', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 15, None),
            ('GIOVANY', 'SOTO AGUIRRE', '1074960367', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 14, None),
            ('ONEIDER FELIPE', 'SOTO RUEDA', '1074960488', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'NOVENO', '901', 13, None),
            ('ESTEFANIA', 'BUSTOS ANZOLA', '1073605220', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 14, None),
            ('SHELSI MICHEL', 'FLORIDO FLORIDO', '1074960129', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 15, None),
            ('JOHN ESTEBAN', 'ROJAS LOZADA', '1077231726', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 16, None),
            ('TANIA KATERINE', 'ROJAS LOZADA', '1077231727', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 16, None),
            ('NICOL SARAY', 'RUBIO FLORIDO', '1022376816', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 15, None),
            ('GINNA NICOLE', 'ALVAREZ RAMIREZ', '1074959552', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 17, None),
            ('LUCIANO', 'AGUIRRE SOTO', '1057390254', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 14, None),
            ('JAVIER CAMILO', 'RODRIGUEZ VEGA', '1074960275', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 15, None),
            ('OSCAR ANDRES', 'BUSTOS ZAMUDIO', '1069730118', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 18, None),
            ('KEVIN YAIR', 'CASTIBLANCO SOTO', '1074960279', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 14, None),
            ('EDGAR DAVID', 'ROMERO CORTES', '1072700127', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 14, None),
            ('EDWARD DAVID', 'OICATA BENAVIDES', '1074980229', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'DÉCIMO', '1001', 15, None),
            ('YEFFERSON', 'BUSTOS PEREZ', '1074959924', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('JOSE EDGAR', 'OBANDO RODRIGUEZ', '1074959095', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 19, None),
            ('ELKIN DAVID', 'RUBIO BONILLA', '1124996541', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 18, None),
            ('RICARDO', 'SOTO AGUIRRE', '1074959990', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('DANIEL FELIPE', 'SUAREZ GARZON', '1071580113', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('KEWIN DAVID', 'TOVAR ALVAREZ', '1074959871', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('JUAN JOSE', 'VEGA VEGA', '1074959781', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('ELCONT RUBIELA', 'ANZOLA VANEGAS', '1021680822', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 16, None),
            ('LUNA ALEJANDRA', 'AVELLANEDA SANTOS', '1003540840', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 22, None),
            ('ANGELICA MARIA', 'GARZON TRIANA', '1074959545', 'INSTITUCION EDUCATIVA DEPARTAMENTAL URIEL MURCIA', 'ONCE', '1101', 17, None),
            ('MICHEL SOFIA', 'LONDOÑO VANEGAS', '1077062878', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'GRADO 0', '1', 4, 'f'),
            ('NARETH LUCIANA', 'TRESPALACIOS ANZOLA', '1074996485', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'GRADO 0', '1', 6, 'f'),
            ('EILEEN CELESTE', 'AGUILAR AGUILAR', '1074996511', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'PRIMERO', '101', 5, 'f'),
            ('ALAN MATEO', 'GONZALEZ BUSTOS', '1055247511', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'PRIMERO', '101', 6, None),
            ('DANNA ISABELLA', 'BUSTOS LOZADA', '1069306977', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEGUNDO', '201', 7, 'f'),
            ('VIVIANA EUDIMAR', 'RIVERA PEREZ', 'N37857047897', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEGUNDO', '201', 7, 'f'),
            ('MAYARY MELISSA', 'SALGADO LOZADA', '1046540455', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEGUNDO', '201', 7, 'f'),
            ('LUCIA', 'VANEGAS CHAPARRO', '1074996442', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEGUNDO', '201', 7, 'f'),
            ('SARAY', 'AGUILLON VEGA', '1074996385', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'TERCERO', '301', 8, 'f'),
            ('SARA SOFIA', 'ACOSTA GOMEZ', '1071144058', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'TERCERO', '301', 11, 'f'),
            ('DYLAN MATIAS', 'MORENO CANO', '1027299317', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'CUARTO', '401', 9, None),
            ('KEYLOR SAMUEL', 'SOTELO BUSTOS', '1023970557', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'CUARTO', '401', 9, None),
            ('FAISON DAVID', 'BUSTOS CASTAÑEDA', '1071170072', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 11, None),
            ('NEYMAR DAVID', 'ANZOLA VANEGAS', '1073607039', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 12, None),
            ('GABRIEL MATIAS', 'LEAL VILLEGAS', '1222208598', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 11, None),
            ('WILDER', 'RUBIO BONILLA', '1072429438', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 12, None),
            ('LEIDY VALERIA', 'ANZOLA VIRGUEZ', '1074995936', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 11, 'f'),
            ('EUTIMIO', 'VEGA CIFUENTES', '1057390230', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 13, None),
            ('SAMARA LUCIA', 'AGUILLON VEGA', '1031837262', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 11, 'f'),
            ('LINDEMEYER', 'ALVAREZ GONZALEZ', '1074960303', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 14, None),
            ('ELMER DAVID', 'ESCARRAGA VANEGAS', '1070708054', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEXTO', '601', 11, None),
            ('MAICOL FERNEY', 'VANEGAS VANEGAS', '1074960519', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEPTIMO', '701', 13, None),
            ('ALISON', 'PUENTES GARZON', '1011222673', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEPTIMO', '701', 13, 'f'),
            ('SEBASTIAN', 'RINCON CASTAÑEDA', '1074816317', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEPTIMO', '701', 13, None),
            ('VALERINE LOREINEN', 'RODRIGUEZ VEGA', '1074960739', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'SEPTIMO', '701', 12, 'f'),
            ('LUNA VALENTINA', 'CIFUENTES TOVAR', '1055246888', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'OCTAVO', '801', 15, 'f'),
            ('ANA MARIA', 'RINCON CASTAÑEDA', '1012921181', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'OCTAVO', '801', 15, 'f'),
            ('BRIYITH YORLEYDI', 'TOVAR FLORIDO', '1074960570', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'OCTAVO', '801', 13, 'f'),
            ('WILSON FERNEY', 'VEGA VANEGAS', '1073605650', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'OCTAVO', '801', 14, None),
            ('CHARY VALENTINA', 'MOSQUERA SANCHEZ', '1056780055', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'NOVENO', '901', 14, 'f'),
            ('JUAN CARLOS', 'TRIANA BUSTOS', '1074960072', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'NOVENO', '901', 15, None),
            ('MIGUEL ANGEL', 'ULLOA VEGA', '1074960502', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'NOVENO', '901', 13, None),
            ('DAVID SANTIAGO', 'VEGA ZARATE', '1074960423', 'INSTITUCION EDUCATIVA POST - PRIMARIA RURAL GUADUALITO', 'NOVENO', '901', 14, None),
        ]
        for nombres, apellidos, doc, sede, grado, grupo, edad, genero in ESTUDIANTES:
            if db.query(models.Estudiante).filter(models.Estudiante.documento == doc).first():
                continue
            est = models.Estudiante(
                nombres=nombres, apellidos=apellidos, documento=doc,
                sede=sede, grado=grado, grupo=grupo,
                edad=edad, genero=genero, activo=True
            )
            db.add(est)
        db.commit()
        print(f"[Import] {db.query(models.Estudiante).count()} estudiantes importados")
    except Exception as e:
        print(f"Error importando estudiantes: {e}")
        db.rollback()
    finally:
        db.close()


crear_admin_inicial()
importar_estudiantes_inicial()

app = FastAPI(
    title="ObservadorUriel API",
    description="Sistema de Observador del Estudiante — IERD Uriel Murcia, Yacopí",
    version="1.0.0",
    redirect_slashes=False,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://observadoruriel.netlify.app",
        "*",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_router)
app.include_router(docentes_router)
app.include_router(estudiantes_router)
app.include_router(anotaciones_router)
app.include_router(reportes_router)


@app.get("/")
def root():
    return {
        "app": "ObservadorUriel",
        "version": "1.0.0",
        "institucion": "IERD Uriel Murcia — Yacopí, Cundinamarca",
        "estado": "activo",
    }


@app.get("/health")
def health():
    return {"status": "ok"}
